
import math


print(2+3)
print(2-3)
print(2*4)
print(2/4)
print(2**2)
print(2%3)
print("sakshi")
print("Ranka")
print("India")
print("30 days of python")
print(type(10))
print(type (9.8))
print(type (3.14))
print(type (4 - 4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type("sakshi"))
print(type("Ranka"))
print(type("India"))
print("30 days of python")
print(2)
print(2.4)
print(2+3j)
print(bool(2+4))
print("sakshi")
print(math.sqrt((2-10)**2)+((3-8)**2))
